### ISSUE TITLE
Provide map link for class locations in exported schedule

### ISSUE THREAD

**Issue by demetrios-koziris** [demetrios-koziris/McGillEnhanced#13]
When exporting a schedule to ICS, the location data is currently just building name and room number. McGIll Enhanced should provide a map link to the building.

**Comment by nicholaspaun** [comment]
I'm not sure if you have a better data source, but Minerva bot and I use this:
https://github.com/zafarali/minerva-bot/blob/master/plugins/building_search/BUILDINGS.js

Actually, I've got a version that is actually valid JSON in this directory:
http://cs.mcgill.ca/~npaun/mnvc-data/

(Maybe all of us could have a common Github repo for our Minerva-related data?)

**Comment by austinhuang0131** [comment]
this issue should be closed
