### ISSUE TITLE
Check if future course page exists or not - headers return 503

### ISSUE THREAD

**Issue by YoungElPaso** [demetrios-koziris/McGillEnhanced#17]
Hi, you alter this code:

https://github.com/demetrios-koziris/McGillEnhanced/blob/master/src/js/addYearMenu.js

to do an AJAX request to see if the page in question exists or not by inspecting its header (it should be 503).

Pretty sure you could do that with something like this: 

``` 
// Example failing url: 
var f = function() {
  jQuery.ajax({
    url: 'http://www.mcgill.ca/study/2017-2018/courses/acct-351',
    type: 'GET',
    success: function(xhr, status) {
      console.log('yay');
    },
    error: function(xhr, status) {
      console.log(xhr.status);
    }
  })
}
```

Sorry no time for a PR :)

**Comment by demetrios-koziris** [comment]
Extension now checks the current year and disactivates it in the menu if the page does not exist then it checks all the years before the current year and once checking is done disactivates (at the same time) all of the ones with pages that do not exist. This is useful for courses like [MATH 180](https://www.mcgill.ca/study/2016-2017/courses/math-180) whose first existing page is 2012-2013. Other examples: [MATH 254](https://www.mcgill.ca/study/2016-2017/courses/math-254), [MATH 427](https://www.mcgill.ca/study/2016-2017/courses/math-427), [MATH 454](https://www.mcgill.ca/study/2016-2017/courses/math-454)

See https://github.com/demetrios-koziris/McGillEnhanced/commit/c1b501ff9a6aa220775ff06a7ececb7978be4164

**Comment by YoungElPaso** [comment]
Nice. I'll close this then.  Kudos @demetrios-koziris
