### ISSUE TITLE
Courses without scheduled times break the DTSTART and DTEND fields 

### ISSUE THREAD

**Issue by thomashillyer** [demetrios-koziris/McGillEnhanced#31]
this course:
![image](https://user-images.githubusercontent.com/8906229/51196581-6e4df880-18bd-11e9-9793-efcf0ac29a97.png)
results in:
<pre>
BEGIN:VEVENT
CLASS:PUBLIC
DESCRIPTION:ECSE Design Project 2.\nProject in TBA
<b>DTSTART:0NaNaNaNTaNaNaN</b>
RRULE:FREQ=WEEKLY;UNTIL=20190412T000000Z;INTERVAL=1
<b>DTEND:0NaNaNaNTaNaNaN</b>
DTSTAMP:20190115T000000Z
LOCATION:TBA
SUMMARY;LANGUAGE=en-us:ECSE457-001 PRO
TRANSP:TRANSPARENT
END:VEVENT
</pre>
which is not accepted by the Google Calendar importer

**Comment by demetrios-koziris** [comment]
Thanks for finding this!
Looks like I incorrectly assumed the Time cell would never be empty or TBA (the code assumes there is a time and end time separated by a '-'). 
Any thoughts on if there's anything elegant to do with such a case other than not adding events for courses that are missing a time? (Making it a full day event or arbitrarily choosing a time definitely don't seem like good ideas but maybe there's something else I'm not thinking of).

**Comment by demetrios-koziris** [comment]
Should be fixed in [v3.3.72](https://github.com/demetrios-koziris/McGillEnhanced/releases/tag/v3.3.72)
