### ISSUE TITLE
Dead link on menu - Docuum

### ISSUE THREAD

**Issue by WiIIiamTang** [demetrios-koziris/McGillEnhanced#37]
The Docuum link is dead. I think the McGill docuum was taken down, dating back to a year ago. It came back for a couple weeks, but now it has been dead for a while now.

**Comment by demetrios-koziris** [comment]
Yeah Docuum seems to go down pretty often. I'm going to wait until the fall 2020 semester stars and if it's not back I'll reevaluate.

**Comment by demetrios-koziris** [comment]
Docuum is back  :)
