### ISSUE TITLE
ICS export button missing on Firefox

### ISSUE THREAD

**Issue by JadedHearth** [demetrios-koziris/McGillEnhanced#57]
Tested on Firefox 131.0 with all extensions disabled. I'd note that it used to work, and just disappeared sometime at least 4 months ago, probably further back than that. It appears properly on Eloston (Ungoogled) Chromium on the same computer, so it's likely a Firefox thing.

**Comment by demetrios-koziris** [comment]
Thanks for reporting! 
Looks like this is for the same reason as #54.
I had a fix in the manifest v3 version but hadn't published that to Firefox yet. 
Did that over the weekend so let me know if you're still hitting this issue or if it's now resolved.

**Comment by demetrios-koziris** [comment]
Should be fixed in [v4.4.6](https://github.com/demetrios-koziris/McGillEnhanced/releases/tag/v4.4.6)
